# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import unter_pb2 as unter__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in unter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UnterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRide = channel.unary_unary(
                '/Unter/StartRide',
                request_serializer=unter__pb2.StartRideRequest.SerializeToString,
                response_deserializer=unter__pb2.StartRideResponse.FromString,
                _registered_method=True)
        self.EndRide = channel.unary_unary(
                '/Unter/EndRide',
                request_serializer=unter__pb2.EndRideRequest.SerializeToString,
                response_deserializer=unter__pb2.EndRideResponse.FromString,
                _registered_method=True)


class UnterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRide(self, request, context):
        """Unary
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRide(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UnterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRide': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRide,
                    request_deserializer=unter__pb2.StartRideRequest.FromString,
                    response_serializer=unter__pb2.StartRideResponse.SerializeToString,
            ),
            'EndRide': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRide,
                    request_deserializer=unter__pb2.EndRideRequest.FromString,
                    response_serializer=unter__pb2.EndRideResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Unter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Unter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Unter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Unter/StartRide',
            unter__pb2.StartRideRequest.SerializeToString,
            unter__pb2.StartRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndRide(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Unter/EndRide',
            unter__pb2.EndRideRequest.SerializeToString,
            unter__pb2.EndRideResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
